### ISSUE TITLE
problem with osmosis

### ISSUE THREAD

**Issue by alex83100** [stereodruid/plugin.video.osmosis#36]
17:55:47.805 T:7008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'filetype' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.osmosis\default.py", line 341, in <module>
                                                create.fillPluginItems(url, strm=True, strm_name=name, strm_type=cType)
                                              File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.osmosis\modules\create.py", line 137, in fillPluginItems
                                                movieList = addMovies(detail, strm_name, strm_type)
                                              File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.osmosis\modules\create.py", line 477, in addMovies
                                                if filetype != 'file' and pagesDone < int(PAGINGMovies):
                                            UnboundLocalError: local variable 'filetype' referenced before assignment
                                            -->End of Python script error report<--

**Comment by Maven85** [comment]
With version 1.3.1 the problem should be solved.
